name: wesal
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl: 0.20.2
  flutter_svg: 2.0.10+1
  cupertino_icons: ^1.0.8
  wesal_ui_system:
    path: ../wesal_ui_system
  preferences:
    path: ../utils/preferences
  flutter_bloc: ^9.1.1
  freezed: ^3.1.0
  freezed_annotation: 3.1.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: ^7.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  fpdart: ^1.1.1
  flutter_holo_date_picker: ^2.0.0
  image_cropper: ^9.1.0
  image: ^4.5.4
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  uuid: ^4.5.1
  flutter_native_splash: ^2.4.4
  fluttertoast: ^8.2.12
  lazy_load_indexed_stack: ^1.2.1
  like_button: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Italic.ttf
  #         style: italic